= csoftz-torre-the-palindrome-challenge-rest :: CSoftZ Torre Palindrome Challenge

This is a _Spring Boot V1.5.3_ application to use create the REST API and an HTML page.

[NOTE]
====
In order to execute this console application, one dependency must be compiled
and installed.

The dependency is the project contained in this sibling folder named _palindrome-lib, 
thus you must go there and execute the README instructions. Besides if you make any modifications
to the source code therein, you must again execute those instructions. As a refresher, this is the command.

[source, terminal]
----
$ cd ..
$ cd palindrome-lib
$ mvn clean package
----

Besides you must have _maven_ propery installed and configured.
====

Compile, deploy and execute executing the following commands.

$ mvn clean package 

The delivery JAR is stored in the TARGET directory with that you can execute the application
by typing the following command.

$ java -jar csoftz-torre-palindrome-rest-1.0.1-RELEASE.jar (version number may change, here it is v1.0.1).

After the apolication load, open an HTTP client like _curl_ or _postman_ to test end points.
Also you can open a web browser to see content.

Open the following urls.

htt://localhost:8092/home to test the application is responding, it will present an HTML with a welcome
screen and a description for end points.

The end points are:

http://localhost:8092/api/v1/palindrome/numbers/range/{start}/{end}

here replace {start} with an initial number in range from 1 to 1000000
and replace {end} with the final number in range with a value from 1 to 1000000.

[NOTE]
====
If x > y the result is an empty list.

If x or y parameters are not valid integers then an HTTP 400 Bad request is returned to client, indicating
that no valid parameters are given.
====

The other available end point is:

http://localhost:8092/api/v1/palindrome/numbers/range

It evaluates implicitely the range 1 to 1000000.

The end points responds a JSON object indicating the parameters used, the palindromes found,
the number of palindromes found and the algorithm complexity.