= csoftz-torre-the-palindrome-challenge-console :: CSoftZ Torre Palindrome Challenge

This is the console application to gather palindrome numbers information.

To compile execute the following command

[NOTE]
====
In order to execute this console application, one dependency must be compiled
and installed.

The dependency is the project contained in this sibling folder named _palindrome-lib, 
thus you must go there and execute the README instructions. Besides if you make any modifications
to the source code therein, you must again execute those instructions. As a refresher, this is the command.

[source, terminal]
----
$ cd ..
$ cd palindrome-lib
$ mvn clean package install
----

Besides you must have _maven_ propery installed and configured.
====

[source, terminal]
----
$ mvn clean package
----

The executable is found in this project's target folder.

Now that it is compiled you can execute the application by typing the following
command.

[source, terminal]
----
$ java -jar csoftz-torre-palindrome-console-1.0.0-RELEASE.jar default
----

This gets the default palindrome numbers between 1 and 1000000.

[source, terminal]
----
$ java -jar csoftz-torre-palindrome-console-1.0.0-RELEASE.jar 2 100
----

This gets the palindrome numbers between 2 100

The application validates input parameters accordingly.
